# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-22 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(choices=[('AV', 'Adventure'), ('CL', 'Classics'), ('GN', 'Graphic Novel'), ('MY', 'Mystery'), ('FN', 'Fantasy'), ('HF', 'Historical Fiction'), ('HR', 'Horror'), ('LF', 'Literary Fiction'), ('RO', 'Romance'), ('SF', 'Science Fiction'), ('TR', 'Thrillers'), ('BG', 'Biographies'), ('CO', 'Cooking'), ('ES', 'Essays'), ('HS', 'History'), ('MR', 'Memoir'), ('PT', 'Poetry'), ('SH', 'Self Help'), ('TC', 'True Crime')], default='AV', max_length=2),
        ),
    ]
