# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-22 02:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0002_auto_20210122_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='published_date',
        ),
        migrations.AddField(
            model_name='product',
            name='year_published',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
